### ISSUE TITLE
存档：原有的全局字体设置

### ISSUE THREAD

**Issue by cssmagic** [UserScript/Oh-My-GitHub#16]
原来的设置：

``` css
body {
    background-color: #ffffff;
    color: #333333;
    font-family: Helvetica,arial,nimbussansl,liberationsans,freesans,clean,sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol";
    font-size: 13px;
    line-height: 1.4;
}
```

现在的设置：

``` css
body {
    background-color: #ffffff;
    color: #333333;
    font-family: -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol";
    font-size: 14px;
    line-height: 1.5;
}
```
